name: Iqbal Adan
description: Blogging about GNU/Linux and Web Developments
meta_description: "Iqbal Adan, Blogging about his interest"

aboutPage: true

markdown: kramdown
highlighter: rouge

paginate: 20
paginate_path: "page:num"
baseurl: /
domain_name: ''
google_analytics: ''
disqus: true
disqus_shortname: 'iqbaladan'

# Details for the RSS feed generator
url:            'http://iqbaladan.github.io'
author:         'Iqbal Adan'
authorTwitter:  'iqbaladan'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: "" # empty string for all files
            type: drafts
        values:
            layout: post

# Gems
gems: [jekyll-paginate]
