# Site settings
title: Iqbal Adan - A blog about technical stuff.
email: iqbal.adan@gmail.com
description: A blog about my favorite web conferences.
url: "" # the base hostname & protocol for your site
twitter_username: iqbaladan
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

#Default settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      author: Iqbal Adan
      layout: "post"
      category: conferences
      comments: true
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously `post` in Jekyll 2.2.
    values:
      layout: "page"





