# Permalinks
permalink:           pretty

# Setup
title:               Iqbal Adan
tagline:             Personal Blog
url:                 
paginate:            1
baseurl:             ""
comments:            True

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# Navigation bar
pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'

# About/contact
author:
  name:              Iqbal Adan
  url:               https://twitter.com/iqbaladan
  email:             iqbal.adan@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/iqbaladan/iqbaladan.github.io

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
