# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Iqbal Adan"
description: > # this means to ignore newlines until "email:"
   A Journal of Linux Fanboy

email: iqbal.adan@gmail.com

permalink: pretty

#blog logo
#logo: "/assets/images/df_logo.jpg"

# blog cover
cover: "/assets/images/front.jpg"

name: 'Iqbal Adan'
author: 'Iqbal Adan'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@iqbaladan'

#fill in disqus shortname to use disqus
disqus: iqbaladan

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/iqbaladan
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:	https://facebook.com/iqbal.adan.3
    desc: Connect with me facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/iqbaladan
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
